/**
 * The heat ramp exists three times and must be one thing.
 *
 * `src/ui/theme.ts` draws the in-app habit grid, `RidikPalette.swift` draws the
 * iOS widget, and the colour XML generated by `plugins/withRidikAndroidWidget.js`
 * draws the Android one. All three are on screen at once — the app open beside
 * its own home-screen tile — and a value that drifted in one of them would put
 * the same grid in two palettes with nothing failing anywhere.
 *
 * There is no shared source they could all import: an Xcode extension links
 * neither the app nor React Native, and an Android resource file is XML. So the
 * agreement is asserted here instead — the Swift by reading it as text, the
 * Android by calling the plugin that writes it and checking what comes out.
 *
 * Both halves of that have been wrong before, in the same way and for the same
 * reason: an assertion that reads something *other* than what ships. The Swift
 * side is genuinely the shipped file. The Android side was, for a while, the
 * plugin's source — and then a hand-written literal inside it that the plugin
 * had stopped using, so it passed while the built widget drew something else.
 * If this file is ever extended, extend it toward the artifact, not away.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { DEFAULT_EMBER, cells, darkColors, embers, lightColors, tile } from '../theme';

/**
 * The ground the ramp is judged against, and the ink judged against the ramp.
 *
 * Imported, not written out. These were literals here for one release and it
 * was the reason the whole suite stayed green through a ground change that had
 * already invalidated every ramp in the file: a test asserting agreement
 * between three copies of a value cannot also hold a fourth of its own.
 */
const GROUND = tile;
const INK: Record<'light' | 'dark', string> = {
  light: lightColors.text,
  dark: darkColors.text,
};

const ROOT = join(__dirname, '..', '..', '..');
const SWIFT = readFileSync(join(ROOT, 'targets/RidikWidget/RidikPalette.swift'), 'utf8');

/**
 * The Android resource files, generated rather than read off disk.
 *
 * `android/` is gitignored and only exists after a prebuild, so reading the
 * written XML meant these assertions errored on a fresh clone and never ran in
 * CI at all — a test that cannot fail is not protecting anything. Calling the
 * plugin's own generator produces the same strings the build would write, with
 * no build step in between.
 */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const RESOURCES: Record<string, string> = require('../../../plugins/withRidikAndroidWidget')
  .resourceFiles();

/**
 * `heatCold: Color(rgb: 0xF7CFB8)` inside a named `static let … = RidikPalette(`
 * block.
 *
 * The default's two are `light` and `dark`; every other ember's are its name and
 * the scheme — `kilnLight`, `rustDark`. Only the first match after the marker is
 * read, so the blocks must stay in the order they are declared in.
 */
function swiftPalette(name: string, field: string): string | null {
  const block = SWIFT.split(`static let ${name} = RidikPalette(`)[1];
  const match = block?.match(new RegExp(`${field}: Color\\(rgb: 0x([0-9A-Fa-f]{6})\\)`));
  return match ? `#${match[1]!.toUpperCase()}` : null;
}

function swiftValue(scheme: 'light' | 'dark', field: string): string | null {
  return swiftPalette(scheme, field);
}

/**
 * Every `ridik_widget_<ember>_heat_<level>` the plugin will write, per scheme.
 *
 * Generated rather than parsed out of a literal: the plugin builds the darker
 * embers' colours from `embers` at run time, so reading only the default's
 * hand-written `heat: {}` block asserted one ramp of three while the comment
 * beside it claimed all of them. A guarantee that is not enforced is worse than
 * none, because it is the reason nobody checks.
 */
function pluginEmberColours(scheme: 'light' | 'dark'): Record<string, string> {
  const written: Record<string, string> = {};
  for (const option of Object.values(embers)) {
    const ramp = option[scheme];
    for (const level of ['cold', 'low', 'mid', 'hot'] as const) {
      written[`${option.name}.${level}`] = ramp[level].toUpperCase();
    }
  }
  return written;
}

/** The generated `values/` or `values-night/` colour table, by resource name. */
function generatedColours(scheme: 'light' | 'dark'): Record<string, string> {
  const dir = scheme === 'light' ? 'values' : 'values-night';
  const xml = RESOURCES[`${dir}/ridik_widget_colors.xml`]!;
  const out: Record<string, string> = {};
  for (const [, name, value] of xml.matchAll(
    /<color name="([^"]+)">(#[0-9A-Fa-f]{6,8})<\/color>/g,
  )) {
    out[name!] = value!.toUpperCase();
  }
  return out;
}

/**
 * The default ember's ramp as Android will actually draw it.
 *
 * Read out of the generated XML rather than out of the plugin's source. It was
 * the source for one release, matched against a hand-written `heat: {}` literal
 * that the plugin no longer uses — so this assertion was reading a value that
 * never reached a device, and stayed green while the shipped ground moved.
 * The generated file is the artifact; nothing sits between it and the launcher.
 */
function pluginHeat(scheme: 'light' | 'dark'): Record<string, string> {
  const generated = generatedColours(scheme);
  const level = ['cold', 'low', 'mid', 'hot'] as const;
  const out: Record<string, string> = { onHeat: generated.ridik_widget_on_heat! };
  level.forEach((name, index) => {
    out[name] = generated[`ridik_widget_${DEFAULT_EMBER}_heat_${index}`]!;
  });
  return out;
}

const SCHEMES = ['light', 'dark'] as const;
const LEVELS = ['cold', 'low', 'mid', 'hot', 'onHeat'] as const;

/** theme.ts `cold` is Swift's `heatCold`; `onHeat` is `onHeat` in both. */
const SWIFT_FIELD: Record<(typeof LEVELS)[number], string> = {
  cold: 'heatCold',
  low: 'heatLow',
  mid: 'heatMid',
  hot: 'heatHot',
  onHeat: 'onHeat',
};

describe('the heat ramp agrees across all three platforms', () => {
  for (const scheme of SCHEMES) {
    for (const level of LEVELS) {
      it(`${scheme} ${level}`, () => {
        const source = cells[scheme][level].toUpperCase();
        expect(swiftValue(scheme, SWIFT_FIELD[level])).toBe(source);
        expect(pluginHeat(scheme)[level]).toBe(source);
      });
    }
  }

  /**
   * And so does the ground they were solved against.
   *
   * This is the assertion the suite was missing. A ramp is six colours over a
   * seventh, so agreeing on the six while disagreeing on the ground is not
   * agreement at all — and that is exactly what shipped: Swift moved to the
   * pale tile while the Android plugin kept writing the app's saturated sand,
   * with every per-ember assertion still green. The two tiles were four points
   * of lightness apart, which is invisible in a diff and obvious on a phone.
   */
  for (const scheme of SCHEMES) {
    it(`${scheme} ground`, () => {
      const source = tile[scheme].toUpperCase();
      expect(swiftValue(scheme, 'tile')).toBe(source);
      expect(generatedColours(scheme).ridik_widget_ground).toBe(source);
    });
  }
});

describe('the ramp holds its own rules', () => {
  /* Ink sits on cold, low and mid; on hot it inverts. Both sides clear 4.5:1.
     Ink on hot measures 3.2:1 — the one pairing that must never be drawn. */
  /* The point of raising the floor: a widget with nothing in it must still read
     as an instrument at rest rather than as a blank card. */
  it('makes a resting cell visible against its own tile', () => {
    for (const scheme of SCHEMES) {
      expect(contrast(cells[scheme].cold, GROUND[scheme])).toBeGreaterThan(1.34);
    }
  });

  /* `onHeat` is the tile itself, so an inverted numeral reads as the ground
     showing through a lit cell rather than as white paint sitting on one. */
  it('inverts to the tile rather than to a colour of its own', () => {
    for (const scheme of SCHEMES) {
      expect(cells[scheme].onHeat.toUpperCase()).toBe(GROUND[scheme].toUpperCase());
    }
  });

  it('keeps text legible on every level it is allowed on', () => {
    for (const scheme of SCHEMES) {
      for (const level of ['cold', 'low', 'mid'] as const) {
        expect(contrast(INK[scheme], cells[scheme][level])).toBeGreaterThanOrEqual(4.5);
      }
      expect(contrast(cells[scheme].onHeat, cells[scheme].hot)).toBeGreaterThanOrEqual(4.5);
    }
  });

  /* Four levels are only worth having if a glance can tell them apart. Every
     step clears 11.5 in perceived lightness; below about 10 they read as noise.
     It was 12 until the resting cell was raised to 23% — an empty tile is the
     state the whole family is judged on, and buying it 14% more presence off
     the ground is worth 0.3 of a step between levels nobody sees side by side. */
  it('spaces the four levels far enough apart to be tellable', () => {
    for (const scheme of SCHEMES) {
      const ramp = (['cold', 'low', 'mid', 'hot'] as const).map((l) => lightness(cells[scheme][l]));
      for (let i = 0; i < ramp.length - 1; i++) {
        expect(Math.abs(ramp[i + 1]! - ramp[i]!)).toBeGreaterThan(11.5);
      }
    }
  });

  /* The dark ramp is the better instrument, which is why dark ships as the
     hero rather than as a concession. */
  it('resolves more clearly in the dark than in the light', () => {
    const spread = (scheme: 'light' | 'dark') =>
      lightness(cells[scheme].hot) - lightness(cells[scheme].cold);
    expect(Math.abs(spread('dark'))).toBeGreaterThan(Math.abs(spread('light')));
  });
});

function channel(hex: string, at: number): number {
  return parseInt(hex.slice(at, at + 2), 16) / 255;
}

function linear(c: number): number {
  return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
}

function luminance(hex: string): number {
  return (
    0.2126 * linear(channel(hex, 1)) +
    0.7152 * linear(channel(hex, 3)) +
    0.0722 * linear(channel(hex, 5))
  );
}

function contrast(a: string, b: string): number {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi! + 0.05) / (lo! + 0.05);
}

/** CIE L*, which is where "a step you can see" is measurable. */
function lightness(hex: string): number {
  const y = luminance(hex);
  return y > 0.008856 ? 116 * y ** (1 / 3) - 16 : 903.3 * y;
}

/**
 * A colour the user can pick is a colour that ships. Every option has to hold
 * the same rules the default does, or choosing one makes your own widgets
 * unreadable and nothing anywhere says so.
 */
describe('every selectable ember is shippable', () => {
  for (const option of Object.values(embers)) {
    describe(option.label, () => {
      for (const scheme of SCHEMES) {
        const ramp = option[scheme];

        it(`${scheme}: a resting cell is visible against its own tile`, () => {
          expect(contrast(ramp.cold, GROUND[scheme])).toBeGreaterThan(1.34);
        });

        it(`${scheme}: the four levels stay tellable apart`, () => {
          const ls = ([ramp.cold, ramp.low, ramp.mid, ramp.hot]).map(lightness);
          for (let i = 0; i < ls.length - 1; i++) {
            expect(Math.abs(ls[i + 1]! - ls[i]!)).toBeGreaterThan(11.5);
          }
        });

        it(`${scheme}: inverted ink is legible on the hot cell`, () => {
          expect(contrast(ramp.onHeat, ramp.hot)).toBeGreaterThanOrEqual(4.5);
        });

        it(`${scheme}: ink is legible on every level the plate may reach`, () => {
          // `platePeak` is the whole reason the darker embers are shippable at
          // all: they cap the plate at `low` in light, where their `mid` cell is
          // too dark for a near-black numeral. Dark has no such limit.
          const peak = scheme === 'dark' || option.platePeak === 'mid' ? ramp.mid : ramp.low;
          expect(contrast(INK[scheme], peak)).toBeGreaterThanOrEqual(4.5);
        });
      }
    });
  }

  /**
   * The plugin must actually emit a colour for every level of every ember.
   *
   * Read out of the generated resource files rather than out of the source, so
   * this fails if the plugin stops writing one — the failure mode is a colour
   * resolving to 0 and a cell drawn transparent, with a green build.
   */
  it('the Android build writes every ember at every level', () => {
    const generated = RESOURCES['values/ridik_widget_colors.xml']!;
    for (const option of Object.values(embers)) {
      for (const level of [0, 1, 2, 3]) {
        expect(generated).toContain(`ridik_widget_${option.name}_heat_${level}`);
      }
      expect(generated).toContain(`ridik_widget_${option.name}_accent`);
    }
  });

  it('and the values it writes are the ones in theme.ts', () => {
    for (const scheme of SCHEMES) {
      const file = scheme === 'light' ? 'values' : 'values-night';
      const generated = RESOURCES[`${file}/ridik_widget_colors.xml`]!;
      for (const [key, hex] of Object.entries(pluginEmberColours(scheme))) {
        const [name, level] = key.split('.') as [string, 'cold' | 'low' | 'mid' | 'hot'];
        const index = { cold: 0, low: 1, mid: 2, hot: 3 }[level];
        const match = generated.match(
          new RegExp(`name="ridik_widget_${name}_heat_${index}">(#[0-9A-Fa-f]{6,8})<`),
        );
        expect(match?.[1]?.toUpperCase()).toBe(hex);
      }
    }
  });

  /* The default is the one that keeps all four levels on the plate everywhere.
     If that ever stops being true, the default is the wrong one. */
  it('defaults to the only ember that needs no compromise', () => {
    expect(embers[DEFAULT_EMBER].platePeak).toBe('mid');
    for (const option of Object.values(embers)) {
      if (option.name !== DEFAULT_EMBER) expect(option.platePeak).toBe('low');
    }
  });
});

/**
 * And every one of them has to exist on the other side, unchanged.
 *
 * A colour the user can pick is a colour three languages now have to agree on,
 * so the same crude read of `RidikPalette.swift` covers all three embers rather
 * than only the one the app shipped with. A ramp that drifted here would put the
 * app in one palette and its own home-screen tile in another, with nothing
 * failing anywhere.
 */
describe('the iOS widget carries every ember', () => {
  /** `kiln` + `Light` — the default's blocks are the bare `light` and `dark`. */
  const blockFor = (name: string, scheme: 'light' | 'dark') =>
    name === DEFAULT_EMBER ? scheme : `${name}${scheme === 'light' ? 'Light' : 'Dark'}`;

  for (const option of Object.values(embers)) {
    for (const scheme of SCHEMES) {
      for (const level of LEVELS) {
        it(`${option.name} ${scheme} ${level}`, () => {
          expect(swiftPalette(blockFor(option.name, scheme), SWIFT_FIELD[level])).toBe(
            option[scheme][level].toUpperCase(),
          );
        });
      }

      /* `accent` is the text-safe ember, and for anything but the default that
         is its ramp's own `hot` — the same rule `makeTheme` applies, so the
         widget's eyebrow and the app's are one colour. */
      if (option.name !== DEFAULT_EMBER) {
        it(`${option.name} ${scheme} accent`, () => {
          expect(swiftPalette(blockFor(option.name, scheme), 'accent')).toBe(
            option[scheme].hot.toUpperCase(),
          );
        });
      }
    }

    /* The plate is the one face with text on a filled cell. Swift caps the load
       with a heat character; `platePeak` names the level. They must say the same
       thing, or a calendar ships with dates nobody can read. */
    it(`${option.name} caps the light plate where the palette says`, () => {
      const capped = swiftPeak(blockFor(option.name, 'light'));
      expect(capped).toBe(option.platePeak === 'mid' ? '2' : '1');
      // Dark has no such constraint, on any ember — so the cap there is '3',
      // which is not a cap at all. It read '2' until an audit noticed that
      // Android's `drawable-night` plate fills from the uncapped ramp: a load
      // level of '3' would have been flattened on one platform and drawn on
      // the other, from the same payload.
      expect(swiftPeak(blockFor(option.name, 'dark'))).toBe('3');
    });
  }
});

/** `platePeak: "1"` inside a named palette block. */
function swiftPeak(name: string): string | null {
  const block = SWIFT.split(`static let ${name} = RidikPalette(`)[1];
  return block?.match(/platePeak: "([0-3])"/)?.[1] ?? null;
}
