/**
 * The heat ramp exists three times and must be one thing.
 *
 * `src/ui/theme.ts` draws the in-app habit grid, `RidikPalette.swift` draws the
 * iOS widget, and the colour XML generated by `plugins/withRidikAndroidWidget.js`
 * draws the Android one. All three are on screen at once — the app open beside
 * its own home-screen tile — and a value that drifted in one of them would put
 * the same grid in two palettes with nothing failing anywhere.
 *
 * There is no shared source they could all import: an Xcode extension links
 * neither the app nor React Native, and an Android resource file is XML. So the
 * agreement is asserted here instead, by reading the other two as text. It is a
 * crude test and it is the only kind available.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { cells } from '../theme';

const ROOT = join(__dirname, '..', '..', '..');
const SWIFT = readFileSync(join(ROOT, 'targets/RidikWidget/RidikPalette.swift'), 'utf8');
const PLUGIN = readFileSync(join(ROOT, 'plugins/withRidikAndroidWidget.js'), 'utf8');

/** `heatCold: Color(rgb: 0xF7CFB8)` inside the `static let light = …` block. */
function swiftValue(scheme: 'light' | 'dark', field: string): string | null {
  const block = SWIFT.split(`static let ${scheme} = RidikPalette(`)[1];
  const match = block?.match(new RegExp(`${field}: Color\\(rgb: 0x([0-9A-Fa-f]{6})\\)`));
  return match ? `#${match[1]!.toUpperCase()}` : null;
}

/** The `heat: { … }` literal inside the light or dark `colors({ … })` call. */
function pluginHeat(scheme: 'light' | 'dark'): Record<string, string> {
  // The night file is written second, so the dark literal is the later one.
  const marker = scheme === 'light' ? "'values/ridik_widget_colors.xml'" : "'values-night/ridik_widget_colors.xml'";
  const after = PLUGIN.split(marker)[1] ?? '';
  const block = after.slice(after.indexOf('heat: {'), after.indexOf('},', after.indexOf('heat: {')));
  const out: Record<string, string> = {};
  for (const [, key, value] of block.matchAll(/(\w+): '(#[0-9A-Fa-f]{6,8})'/g)) {
    out[key!] = value!.toUpperCase();
  }
  return out;
}

const SCHEMES = ['light', 'dark'] as const;
const LEVELS = ['cold', 'low', 'mid', 'hot', 'onHeat'] as const;

/** theme.ts `cold` is Swift's `heatCold`; `onHeat` is `onHeat` in both. */
const SWIFT_FIELD: Record<(typeof LEVELS)[number], string> = {
  cold: 'heatCold',
  low: 'heatLow',
  mid: 'heatMid',
  hot: 'heatHot',
  onHeat: 'onHeat',
};

describe('the heat ramp agrees across all three platforms', () => {
  for (const scheme of SCHEMES) {
    for (const level of LEVELS) {
      it(`${scheme} ${level}`, () => {
        const source = cells[scheme][level].toUpperCase();
        expect(swiftValue(scheme, SWIFT_FIELD[level])).toBe(source);
        expect(pluginHeat(scheme)[level]).toBe(source);
      });
    }
  }
});

describe('the ramp holds its own rules', () => {
  /* Ink sits on cold, low and mid; on hot it inverts. Both sides clear 4.5:1.
     Ink on hot measures 3.2:1 — the one pairing that must never be drawn. */
  it('keeps text legible on every level it is allowed on', () => {
    const ink = { light: '#2E1508', dark: '#FFEEDF' } as const;
    for (const scheme of SCHEMES) {
      for (const level of ['cold', 'low', 'mid'] as const) {
        expect(contrast(ink[scheme], cells[scheme][level])).toBeGreaterThanOrEqual(4.5);
      }
      expect(contrast(cells[scheme].onHeat, cells[scheme].hot)).toBeGreaterThanOrEqual(4.5);
    }
  });

  /* Four levels are only worth having if a glance can tell them apart. Every
     step clears 12 in perceived lightness; below about 10 they read as noise. */
  it('spaces the four levels far enough apart to be tellable', () => {
    for (const scheme of SCHEMES) {
      const ramp = (['cold', 'low', 'mid', 'hot'] as const).map((l) => lightness(cells[scheme][l]));
      for (let i = 0; i < ramp.length - 1; i++) {
        expect(Math.abs(ramp[i + 1]! - ramp[i]!)).toBeGreaterThan(12);
      }
    }
  });

  /* The dark ramp is the better instrument, which is why dark ships as the
     hero rather than as a concession. */
  it('resolves more clearly in the dark than in the light', () => {
    const spread = (scheme: 'light' | 'dark') =>
      lightness(cells[scheme].hot) - lightness(cells[scheme].cold);
    expect(Math.abs(spread('dark'))).toBeGreaterThan(Math.abs(spread('light')));
  });
});

function channel(hex: string, at: number): number {
  return parseInt(hex.slice(at, at + 2), 16) / 255;
}

function linear(c: number): number {
  return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
}

function luminance(hex: string): number {
  return (
    0.2126 * linear(channel(hex, 1)) +
    0.7152 * linear(channel(hex, 3)) +
    0.0722 * linear(channel(hex, 5))
  );
}

function contrast(a: string, b: string): number {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi! + 0.05) / (lo! + 0.05);
}

/** CIE L*, which is where "a step you can see" is measurable. */
function lightness(hex: string): number {
  const y = luminance(hex);
  return y > 0.008856 ? 116 * y ** (1 / 3) - 16 : 903.3 * y;
}
