/**
 * Puts the database into Android's device backup, which excluded it silently.
 *
 * ## The bug
 *
 * The manifest says `allowBackup="true"`, so the app looks backed up. But it
 * also points at rules files that come from **expo-secure-store**, a transitive
 * dependency, and those say:
 *
 *     <include domain="sharedpref" path="."/>
 *     <exclude domain="sharedpref" path="SecureStore"/>
 *
 * Android's rule is that the moment *any* `<include>` exists, everything not
 * included is excluded. That include names shared preferences and nothing else,
 * so `files/SQLite/ridik.db` — the entire product — was outside the backup set.
 *
 * Nothing reports this. `allowBackup="true"` is still true, the backup runs,
 * and it contains preferences. The failure only appears when somebody loses a
 * phone, restores onto a new one, and finds every note, task, event and habit
 * gone. iOS, meanwhile, writes to `Documents/` and is restored by iCloud
 * without any of this — so the two platforms disagreed about whether the user's
 * data survives a lost phone, which is also the repo's own "both platforms must
 * look the same" rule broken in the most expensive place it could be.
 *
 * ## Why a plugin
 *
 * `android/` is regenerated from the template on every `prebuild --clean`, so a
 * hand-edited XML file reverts and the data-loss returns without a diff. The
 * rules have to be *generated*.
 *
 * ## What is included, and what is deliberately not
 *
 *   include  domain="database"  — anything expo-sqlite puts in the classic
 *                                 databases/ directory.
 *   include  domain="file" path="SQLite"
 *                                 — where expo-sqlite actually writes on this
 *                                   app: `files/SQLite/ridik.db`. Both are
 *                                   listed because the location has moved
 *                                   between SDK versions and an include naming
 *                                   a directory that does not exist is inert,
 *                                   while a missing one loses everything.
 *   include  domain="sharedpref" — kept from the file this replaces. Removing
 *                                   it would drop the app's preferences from a
 *                                   backup that used to contain them.
 *   exclude  domain="sharedpref" path="SecureStore"
 *                                 — expo-secure-store's own exclusion, kept
 *                                   verbatim. Its values are encrypted with a
 *                                   key held in the device keystore, which does
 *                                   NOT travel; restoring them onto a new phone
 *                                   yields ciphertext nothing can read. It is
 *                                   also where the trial and top-up ledgers'
 *                                   durable copies live, and a restorable copy
 *                                   of a spend counter is a refund button.
 *
 * `deviceTransferMode="allowed"` on the API 31+ rules covers phone-to-phone
 * transfer, which is a different code path from cloud backup and the one most
 * people actually use when they upgrade.
 *
 * ## The disclosure this creates
 *
 * The consent screen says the data lives in one file on this device. With this
 * enabled it is also in the user's own Google account. That sentence had to
 * change with this plugin, and it did — see `ConsentScreen.tsx`. Shipping the
 * backup without the sentence would make the app's central privacy claim false.
 */
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

const BACKUP_RULES = 'ridik_backup_rules';
const EXTRACTION_RULES = 'ridik_data_extraction_rules';

/** API 30 and lower. One flat include list; first `<include>` wins the argument. */
const FULL_BACKUP_CONTENT = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withRidikAndroidBackup.js. Do not edit: android/ is
     regenerated by \`expo prebuild\` and this file goes with it. -->
<full-backup-content>
  <include domain="database" path="." />
  <include domain="file" path="SQLite" />
  <include domain="sharedpref" path="." />
  <exclude domain="sharedpref" path="SecureStore" />
</full-backup-content>
`;

/** API 31 and up. Cloud backup and device transfer are declared separately. */
const DATA_EXTRACTION_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withRidikAndroidBackup.js. Do not edit. -->
<data-extraction-rules>
  <cloud-backup>
    <include domain="database" path="." />
    <include domain="file" path="SQLite" />
    <include domain="sharedpref" path="." />
    <exclude domain="sharedpref" path="SecureStore" />
  </cloud-backup>
  <device-transfer>
    <include domain="database" path="." />
    <include domain="file" path="SQLite" />
    <include domain="sharedpref" path="." />
    <exclude domain="sharedpref" path="SecureStore" />
  </device-transfer>
</data-extraction-rules>
`;

function writeRules(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, `${BACKUP_RULES}.xml`), FULL_BACKUP_CONTENT, 'utf8');
      fs.writeFileSync(
        path.join(xmlDir, `${EXTRACTION_RULES}.xml`),
        DATA_EXTRACTION_RULES,
        'utf8',
      );
      return cfg;
    },
  ]);
}

function pointManifestAtThem(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    // Overwritten rather than merged: expo-secure-store's manifest sets these
    // to its own files, and the merger keeps whichever value it sees. Naming
    // ours explicitly is what makes the outcome independent of merge order.
    app.$['android:allowBackup'] = 'true';
    app.$['android:fullBackupContent'] = `@xml/${BACKUP_RULES}`;
    app.$['android:dataExtractionRules'] = `@xml/${EXTRACTION_RULES}`;
    return cfg;
  });
}

module.exports = function withRidikAndroidBackup(config) {
  return pointManifestAtThem(writeRules(config));
};
